/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.komisija;

import domen.Kandidat;
import domen.Karton;
import domen.Zadatak;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;

import modeli.ModelTabelePretragaKartona;
import pomoc.Boja;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author PC
 */
public class FormaPretragaKartona extends javax.swing.JFrame {

    Karton karton;
    int[] redniBrojevi;

    /**
     * Creates new form FormaPretragaKartona
     */
    public FormaPretragaKartona() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x = tk.getScreenSize().width;
        int y = tk.getScreenSize().height;
        setSize(x, y);
        panelZaNestajanje.setVisible(false);
        panelZaNestajanje2.setVisible(false);
        btnUnosCentralneKomisije.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlavni = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKartonskiBroj = new javax.swing.JTextField();
        btnNadjiKarton = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        panelZaNestajanje = new javax.swing.JPanel();
        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSifraPrijave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblGrupaZadataka = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZadataka = new javax.swing.JTable();
        lblTest = new javax.swing.JLabel();
        panelZaNestajanje2 = new javax.swing.JPanel();
        lblIme2 = new javax.swing.JLabel();
        lblPrezime2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSifraPrijave2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblGrupaZadataka2 = new javax.swing.JLabel();
        lblTest2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaZadataka2 = new javax.swing.JTable();
        btnUnosCentralneKomisije = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGlavni.setBackground(new java.awt.Color(204, 204, 204));
        panelGlavni.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Molimo unesite kartonski broj:");
        panelGlavni.add(jLabel1);
        jLabel1.setBounds(170, 40, 182, 17);

        txtKartonskiBroj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtKartonskiBroj.setForeground(new java.awt.Color(102, 102, 102));
        panelGlavni.add(txtKartonskiBroj);
        txtKartonskiBroj.setBounds(390, 30, 130, 40);

        btnNadjiKarton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNadjiKarton.setForeground(new java.awt.Color(102, 102, 102));
        btnNadjiKarton.setText("Nadji karton");
        btnNadjiKarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadjiKartonActionPerformed(evt);
            }
        });
        panelGlavni.add(btnNadjiKarton);
        btnNadjiKarton.setBounds(650, 30, 190, 40);

        btnNazad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNazad.setForeground(new java.awt.Color(102, 102, 102));
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });
        panelGlavni.add(btnNazad);
        btnNazad.setBounds(1030, 30, 180, 40);

        panelZaNestajanje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Sifra prijave:");

        lblSifraPrijave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSifraPrijave.setForeground(new java.awt.Color(102, 102, 102));
        lblSifraPrijave.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Grupa zadataka:");

        lblGrupaZadataka.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGrupaZadataka.setForeground(new java.awt.Color(102, 102, 102));
        lblGrupaZadataka.setText("jLabel4");

        tabelaZadataka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaZadataka);

        lblTest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTest.setForeground(new java.awt.Color(102, 102, 102));
        lblTest.setText("jLabel4");

        javax.swing.GroupLayout panelZaNestajanjeLayout = new javax.swing.GroupLayout(panelZaNestajanje);
        panelZaNestajanje.setLayout(panelZaNestajanjeLayout);
        panelZaNestajanjeLayout.setHorizontalGroup(
            panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZaNestajanjeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelZaNestajanjeLayout.createSequentialGroup()
                        .addGroup(panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelZaNestajanjeLayout.createSequentialGroup()
                                .addGroup(panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelZaNestajanjeLayout.createSequentialGroup()
                                        .addComponent(lblIme)
                                        .addGap(28, 28, 28)
                                        .addComponent(lblPrezime))
                                    .addComponent(jLabel2))
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelZaNestajanjeLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)))
                        .addGroup(panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelZaNestajanjeLayout.createSequentialGroup()
                                .addComponent(lblGrupaZadataka, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lblTest, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSifraPrijave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelZaNestajanjeLayout.setVerticalGroup(
            panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZaNestajanjeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelZaNestajanjeLayout.createSequentialGroup()
                        .addGroup(panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIme)
                            .addComponent(lblPrezime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(lblSifraPrijave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrupaZadataka, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panelGlavni.add(panelZaNestajanje);
        panelZaNestajanje.setBounds(150, 100, 520, 460);

        panelZaNestajanje2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Sifra prijave:");

        lblSifraPrijave2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSifraPrijave2.setForeground(new java.awt.Color(102, 102, 102));
        lblSifraPrijave2.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Grupa zadataka:");

        lblGrupaZadataka2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGrupaZadataka2.setForeground(new java.awt.Color(102, 102, 102));
        lblGrupaZadataka2.setText("jLabel6");

        lblTest2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTest2.setForeground(new java.awt.Color(102, 102, 102));
        lblTest2.setText("jLabel6");

        tabelaZadataka2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaZadataka2);

        javax.swing.GroupLayout panelZaNestajanje2Layout = new javax.swing.GroupLayout(panelZaNestajanje2);
        panelZaNestajanje2.setLayout(panelZaNestajanje2Layout);
        panelZaNestajanje2Layout.setHorizontalGroup(
            panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZaNestajanje2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelZaNestajanje2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblIme2)
                        .addGap(28, 28, 28)
                        .addComponent(lblPrezime2))
                    .addGroup(panelZaNestajanje2Layout.createSequentialGroup()
                        .addGroup(panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelZaNestajanje2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblGrupaZadataka2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelZaNestajanje2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblSifraPrijave2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelZaNestajanje2Layout.setVerticalGroup(
            panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZaNestajanje2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme2)
                    .addComponent(lblPrezime2))
                .addGroup(panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelZaNestajanje2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSifraPrijave2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(lblTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelZaNestajanje2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelZaNestajanje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGrupaZadataka2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        panelGlavni.add(panelZaNestajanje2);
        panelZaNestajanje2.setBounds(700, 100, 520, 460);

        btnUnosCentralneKomisije.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUnosCentralneKomisije.setForeground(new java.awt.Color(102, 102, 102));
        btnUnosCentralneKomisije.setText("Unesi ispravan karton");
        btnUnosCentralneKomisije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosCentralneKomisijeActionPerformed(evt);
            }
        });
        panelGlavni.add(btnUnosCentralneKomisije);
        btnUnosCentralneKomisije.setBounds(1000, 590, 210, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        panelGlavni.add(jLabel6);
        jLabel6.setBounds(0, 0, 1430, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGlavni, javax.swing.GroupLayout.PREFERRED_SIZE, 1437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlavni, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        FormaZaKomisiju fzk = new FormaZaKomisiju();
        fzk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnNadjiKartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadjiKartonActionPerformed
        // TODO add your handling code here:
        String kb = txtKartonskiBroj.getText();
        int kartonskiBroj = Integer.parseInt(kb);
//       
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setParametar(kartonskiBroj);
        kz.setOperacija(Operacije.VRATI_KARTONE_PROVERA);

        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);

        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        ArrayList<Karton> kartoni = (ArrayList<Karton>) so.getOdgovor();

        if (kartoni != null) {
            btnUnosCentralneKomisije.setVisible(true);
            karton = kartoni.get(0);
            ArrayList<Zadatak> zadaciKartona = karton.getListaOdg();
            Karton karton2 = kartoni.get(1);
            ArrayList<Zadatak> zadaciKartona2 = karton2.getListaOdg();
            int brojOdgovora = zadaciKartona.size();
            int brojNeispravnih = 0;
            for (int m = 0; m < brojOdgovora; m++) {
                if (zadaciKartona.get(m).getOdgovor() != zadaciKartona2.get(m).getOdgovor()) {
                    brojNeispravnih++;
                }
            }
            
            if(brojNeispravnih ==0){
                btnUnosCentralneKomisije.setEnabled(false);
            }else{
                btnUnosCentralneKomisije.setEnabled(true);
                
            }
            redniBrojevi = new int[brojNeispravnih];
            int i = 0;
            for (int m = 0; m < brojOdgovora; m++) {
                if (zadaciKartona.get(m).getOdgovor() != zadaciKartona2.get(m).getOdgovor()) {
                    redniBrojevi[i] = zadaciKartona.get(m).getRbZadatka() - 1;
                    i++;
                }
            }

            Kandidat kand = karton.getKandidat();
            if (kand == null) {
                lblSifraPrijave.setText("Karton jos uvek nije spojen sa kandidatom!");
            } else {
                lblIme.setText(kand.getIme());
                lblPrezime.setText(kand.getPrezime());
                lblSifraPrijave.setText(kand.getSifraPrijave());
            }
            panelZaNestajanje.setVisible(true);
            lblGrupaZadataka.setText(karton.getGrupaZadataka().getBrGrupe() + "");
            lblTest.setText(karton.getGrupaZadataka().getTest().getNazivTesta());

            ModelTabelePretragaKartona mtr = new ModelTabelePretragaKartona();
            mtr.setZadaci(zadaciKartona);
            tabelaZadataka.setModel(mtr);
            TableColumn col = tabelaZadataka.getColumnModel().getColumn(1);
            col.setCellRenderer(new Boja(redniBrojevi));

            Kandidat kand2 = karton.getKandidat();
            if (kand2 == null) {
                lblSifraPrijave2.setText("Karton jos uvek nije spojen sa kandidatom!");
            } else {
                lblIme2.setText(kand2.getIme());
                lblPrezime2.setText(kand2.getPrezime());
                lblSifraPrijave2.setText(kand2.getSifraPrijave());
            }

            panelZaNestajanje2.setVisible(true);
            lblGrupaZadataka2.setText(karton2.getGrupaZadataka().getBrGrupe() + "");
            lblTest2.setText(karton2.getGrupaZadataka().getTest().getNazivTesta());

            ModelTabelePretragaKartona mtr2 = new ModelTabelePretragaKartona();
            mtr2.setZadaci(zadaciKartona2);
            tabelaZadataka2.setModel(mtr2);
            TableColumn col2 = tabelaZadataka2.getColumnModel().getColumn(1);
            col2.setCellRenderer(new Boja(redniBrojevi));
        } else {
            JOptionPane.showMessageDialog(this, "Kartoni sa takvim kratonskim brojevima ne postoje u bazi!");
            return;
        }


    }//GEN-LAST:event_btnNadjiKartonActionPerformed

    private void btnUnosCentralneKomisijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosCentralneKomisijeActionPerformed
        // TODO add your handling code here:
        FormaCentralnaKomisija fck = new FormaCentralnaKomisija();
        fck.setKarton(karton);
        fck.setRedniBrojevi(redniBrojevi);
        fck.srediSve();
        this.setVisible(false);
        fck.setVisible(true);
    }//GEN-LAST:event_btnUnosCentralneKomisijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPretragaKartona().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNadjiKarton;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnUnosCentralneKomisije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGrupaZadataka;
    private javax.swing.JLabel lblGrupaZadataka2;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblIme2;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JLabel lblPrezime2;
    private javax.swing.JLabel lblSifraPrijave;
    private javax.swing.JLabel lblSifraPrijave2;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JPanel panelGlavni;
    private javax.swing.JPanel panelZaNestajanje;
    private javax.swing.JPanel panelZaNestajanje2;
    private javax.swing.JTable tabelaZadataka;
    private javax.swing.JTable tabelaZadataka2;
    private javax.swing.JTextField txtKartonskiBroj;
    // End of variables declaration//GEN-END:variables
}
