/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.komisija;

import domen.Karton;
import domen.PomocIzmena;
import domen.Zadatak;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import modeli.ModelTabeleIzmenaKartona;
import modeli.ModelTabeleIzmenaOdCentralneKom;
import pomoc.Boja;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author PC
 */
public class FormaCentralnaKomisija extends javax.swing.JFrame {
    int kartonID;
    Karton karton;
    int[] redniBrojevi;

    /**
     * Creates new form FormaCentralnaKomisija
     */
    public FormaCentralnaKomisija() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x = tk.getScreenSize().width;
        int y = tk.getScreenSize().height;
        setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZadataka = new javax.swing.JTable();
        btnSacuvajIzmene = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblBrojKartona = new javax.swing.JLabel();
        lblGrupaZadataka = new javax.swing.JLabel();
        btnNazad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        tabelaZadataka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaZadataka);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(310, 320, 452, 260);

        btnSacuvajIzmene.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSacuvajIzmene.setForeground(new java.awt.Color(153, 153, 153));
        btnSacuvajIzmene.setText("Sacuvaj izmene");
        btnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIzmeneActionPerformed(evt);
            }
        });
        jPanel2.add(btnSacuvajIzmene);
        btnSacuvajIzmene.setBounds(840, 330, 220, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Broj kartona: ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(330, 180, 126, 22);

        lblBrojKartona.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(lblBrojKartona);
        lblBrojKartona.setBounds(560, 142, 240, 60);

        lblGrupaZadataka.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(lblGrupaZadataka);
        lblGrupaZadataka.setBounds(560, 222, 230, 50);

        btnNazad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNazad.setForeground(new java.awt.Color(153, 153, 153));
        btnNazad.setText("Nazad na glavnu formu");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });
        jPanel2.add(btnNazad);
        btnNazad.setBounds(840, 390, 217, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Grupa zadataka:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(330, 250, 149, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ISPRAVKA OD STRANE CENTRALNE KOMISIJE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(330, 30, 554, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 0, 1900, 1020);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        FormaZaKomisiju fzk = new FormaZaKomisiju();
        this.setVisible(false);
        fzk.setVisible(true);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajIzmeneActionPerformed
        // TODO add your handling code here:
        PomocIzmena pi = new PomocIzmena();
        pi.setKratonId(kartonID);
        ModelTabeleIzmenaOdCentralneKom mtik = (ModelTabeleIzmenaOdCentralneKom) tabelaZadataka.getModel();
        ArrayList<Zadatak> zadaciZaIzmenu = mtik.getZadaciZaIzmenu();
        if(zadaciZaIzmenu.size()==0){
            JOptionPane.showMessageDialog(this, "Morate prvo izmeniti karton!");
            return;
        }
        pi.setZadaciZaIzmenu(zadaciZaIzmenu);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.IZMENI_ZADATKE);
        kz.setParametar(pi);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        JOptionPane.showMessageDialog(this, so.getPoruka());
        return;
    }//GEN-LAST:event_btnSacuvajIzmeneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaCentralnaKomisija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaCentralnaKomisija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaCentralnaKomisija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaCentralnaKomisija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaCentralnaKomisija().setVisible(true);
            }
        });
    }

    public void setKarton(Karton karton) {
        this.karton = karton;
    }

    public void setRedniBrojevi(int[] redniBrojevi) {
        this.redniBrojevi = redniBrojevi;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnSacuvajIzmene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojKartona;
    private javax.swing.JLabel lblGrupaZadataka;
    private javax.swing.JTable tabelaZadataka;
    // End of variables declaration//GEN-END:variables

    public void srediSve() {
        
            kartonID = karton.getKartonID();
            lblGrupaZadataka.setText(karton.getGrupaZadataka().getBrGrupe()+"");
            lblBrojKartona.setText(karton.getBrKartona()+"");
            
            ArrayList<Zadatak> zadaciKartona = karton.getListaOdg();
            ModelTabeleIzmenaOdCentralneKom mtr = new ModelTabeleIzmenaOdCentralneKom();
            mtr.setFck(this);
            mtr.setZadaci(zadaciKartona);
            tabelaZadataka.setModel(mtr);
            TableColumn col = tabelaZadataka.getColumnModel().getColumn(1);
            col.setCellRenderer(new Boja(redniBrojevi));
    }
    
    public void obavestiLength() {
        JOptionPane.showMessageDialog(this, "Mozete uneti samo jednu vrednost!");
      return;
    }

    public void obavesti() {
         JOptionPane.showMessageDialog(this, "Mozete uneti A, B, C, D, E ili N");
      return;
    }
}
