/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.komisija;

import domen.Kandidat;
import domen.Karton;
import domen.Zadatak;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import modeli.ModelTabeleIzmenaKartona;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author PC
 */
public class FormaIzmenaKartona extends javax.swing.JFrame {

    /**
     * Creates new form FormaIzmenaKartona
     */
    public FormaIzmenaKartona() {
        initComponents();
         Toolkit tk = Toolkit.getDefaultToolkit();
        int x = tk.getScreenSize().width;
        int y = tk.getScreenSize().height;
        setSize(x, y);
        PanelDrugi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrvi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKartonskiBroj = new javax.swing.JTextField();
        btnNadji = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        PanelDrugi = new javax.swing.JPanel();
        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSifraPrijave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblGrupa = new javax.swing.JLabel();
        lblTest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZadaci = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnIzmeniKarton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrvi.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Molimo unesite kartonski broj:");

        btnNadji.setText("Nadji");
        btnNadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadjiActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrviLayout = new javax.swing.GroupLayout(PanelPrvi);
        PanelPrvi.setLayout(PanelPrviLayout);
        PanelPrviLayout.setHorizontalGroup(
            PanelPrviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrviLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtKartonskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnNadji)
                .addGap(43, 43, 43)
                .addComponent(btnNazad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrviLayout.setVerticalGroup(
            PanelPrviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrviLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelPrviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKartonskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNadji)
                    .addComponent(btnNazad))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        PanelDrugi.setBackground(new java.awt.Color(153, 153, 153));

        lblIme.setText("jLabel2");

        lblPrezime.setText("jLabel2");

        jLabel2.setText("Sifra prijave:");

        lblSifraPrijave.setText("jLabel3");

        jLabel3.setText("Grupa zadataka:");

        lblGrupa.setText("jLabel4");

        lblTest.setText("jLabel4");

        tabelaZadaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaZadaci);

        jLabel4.setText("Napomena: ukoliko izmenite odgovore, ponovo izracunajte ukupan broj poena kandidata!");

        btnIzmeniKarton.setText("Izmeni karton");

        javax.swing.GroupLayout PanelDrugiLayout = new javax.swing.GroupLayout(PanelDrugi);
        PanelDrugi.setLayout(PanelDrugiLayout);
        PanelDrugiLayout.setHorizontalGroup(
            PanelDrugiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDrugiLayout.createSequentialGroup()
                .addGroup(PanelDrugiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDrugiLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelDrugiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblIme)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(PanelDrugiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDrugiLayout.createSequentialGroup()
                                .addComponent(lblGrupa)
                                .addGap(27, 27, 27)
                                .addComponent(lblTest))
                            .addComponent(lblPrezime)
                            .addGroup(PanelDrugiLayout.createSequentialGroup()
                                .addComponent(lblSifraPrijave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                                .addComponent(btnIzmeniKarton))))
                    .addGroup(PanelDrugiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDrugiLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(96, 96, 96))
        );
        PanelDrugiLayout.setVerticalGroup(
            PanelDrugiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDrugiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDrugiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme)
                    .addComponent(lblPrezime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDrugiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSifraPrijave)
                    .addComponent(btnIzmeniKarton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDrugiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblGrupa)
                    .addComponent(lblTest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrvi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDrugi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDrugi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        FormaZaKomisiju fzk = new FormaZaKomisiju();
        fzk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnNadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadjiActionPerformed
        // TODO add your handling code here:
         String kb =txtKartonskiBroj.getText();
        int kartonskiBroj = Integer.parseInt(kb);
//       
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setParametar(kartonskiBroj);
        kz.setOperacija(Operacije.VRATI_KARTON);
        
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        Karton karton = (Karton) so.getOdgovor();
        if(karton!=null){
            Kandidat kand = karton.getKandidat();
            if(kand==null){
                lblSifraPrijave.setText("Karton jos uvek nije spojen sa kandidatom!");
            }else{
                lblIme.setText(kand.getIme());
                lblPrezime.setText(kand.getPrezime());
                lblSifraPrijave.setText(kand.getSifraPrijave());
            }
            PanelDrugi.setVisible(true);
            lblGrupa.setText(karton.getGrupaZadataka().getBrGrupe()+"");
            lblTest.setText(karton.getGrupaZadataka().getTest().getNazivTesta());
            
            ArrayList<Zadatak> zadaciKartona = karton.getListaOdg();
            ModelTabeleIzmenaKartona mtr = new ModelTabeleIzmenaKartona();
            mtr.setZadaci(zadaciKartona);
            tabelaZadaci.setModel(mtr);
        }else{
            JOptionPane.showMessageDialog(this, "Karton sa takvim kratonskim brojem ne postoji u bazi!");
            return;
       }

    }//GEN-LAST:event_btnNadjiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaIzmenaKartona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDrugi;
    private javax.swing.JPanel PanelPrvi;
    private javax.swing.JButton btnIzmeniKarton;
    private javax.swing.JButton btnNadji;
    private javax.swing.JButton btnNazad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrupa;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JLabel lblSifraPrijave;
    private javax.swing.JLabel lblTest;
    private javax.swing.JTable tabelaZadaci;
    private javax.swing.JTextField txtKartonskiBroj;
    // End of variables declaration//GEN-END:variables

    public void obavestiLength() {
        JOptionPane.showMessageDialog(this, "Mozete uneti samo jednu vrednost!");
      return;
    }

    public void obavesti() {
         JOptionPane.showMessageDialog(this, "Mozete uneti A, B, C, D, E ili N");
      return;
    }
}
