/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.komisija;

import domen.Kandidat;
import domen.Karton;
import domen.PomocIzmena;
import domen.Zadatak;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import modeli.ModelTabeleIzmenaKartona;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author PC
 */
public class FormaIzmenaKartona extends javax.swing.JFrame {
    
    int kartonID;

    /**
     * Creates new form FormaIzmenaKartona
     */
    public FormaIzmenaKartona() {
        initComponents();
         Toolkit tk = Toolkit.getDefaultToolkit();
        int x = tk.getScreenSize().width;
        int y = tk.getScreenSize().height;
        setSize(x, y);
        panelDrugi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrvi = new javax.swing.JPanel();
        btnNadji = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        txtKartonskiBroj = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelDrugi = new javax.swing.JPanel();
        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        lblTest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZadaci = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnIzmeniKarton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSifraPrijave = new javax.swing.JLabel();
        lblGrupa = new javax.swing.JLabel();
        labelaSlika = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrvi.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrvi.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretrazi karton"));
        PanelPrvi.setLayout(null);

        btnNadji.setForeground(new java.awt.Color(102, 102, 102));
        btnNadji.setText("Nadji");
        btnNadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadjiActionPerformed(evt);
            }
        });
        PanelPrvi.add(btnNadji);
        btnNadji.setBounds(540, 30, 90, 30);

        btnNazad.setForeground(new java.awt.Color(102, 102, 102));
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });
        PanelPrvi.add(btnNazad);
        btnNazad.setBounds(660, 30, 90, 30);

        txtKartonskiBroj.setForeground(new java.awt.Color(102, 102, 102));
        txtKartonskiBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKartonskiBrojActionPerformed(evt);
            }
        });
        PanelPrvi.add(txtKartonskiBroj);
        txtKartonskiBroj.setBounds(230, 30, 190, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Molimo unesite kartonski broj:");
        PanelPrvi.add(jLabel1);
        jLabel1.setBounds(20, 30, 200, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        PanelPrvi.add(jLabel5);
        jLabel5.setBounds(10, 20, 1400, 50);

        panelDrugi.setLayout(null);
        panelDrugi.add(lblIme);
        lblIme.setBounds(27, 11, 0, 0);
        panelDrugi.add(lblPrezime);
        lblPrezime.setBounds(136, 11, 0, 0);

        lblTest.setForeground(new java.awt.Color(102, 102, 102));
        panelDrugi.add(lblTest);
        lblTest.setBounds(720, 80, 160, 50);

        jScrollPane1.setForeground(new java.awt.Color(102, 102, 102));

        tabelaZadaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaZadaci);

        panelDrugi.add(jScrollPane1);
        jScrollPane1.setBounds(250, 150, 590, 394);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Napomena: ukoliko izmenite odgovore, ponovo izracunajte ukupan broj poena kandidata!");
        panelDrugi.add(jLabel4);
        jLabel4.setBounds(250, 560, 790, 22);

        btnIzmeniKarton.setBackground(new java.awt.Color(153, 153, 153));
        btnIzmeniKarton.setForeground(new java.awt.Color(102, 102, 102));
        btnIzmeniKarton.setText("Izmeni karton");
        btnIzmeniKarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniKartonActionPerformed(evt);
            }
        });
        panelDrugi.add(btnIzmeniKarton);
        btnIzmeniKarton.setBounds(960, 160, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Sifra prijave:");
        panelDrugi.add(jLabel2);
        jLabel2.setBounds(60, 30, 130, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Grupa zadataka:");
        panelDrugi.add(jLabel3);
        jLabel3.setBounds(60, 100, 150, 17);

        lblSifraPrijave.setForeground(new java.awt.Color(102, 102, 102));
        panelDrugi.add(lblSifraPrijave);
        lblSifraPrijave.setBounds(220, 20, 270, 50);

        lblGrupa.setForeground(new java.awt.Color(102, 102, 102));
        panelDrugi.add(lblGrupa);
        lblGrupa.setBounds(220, 80, 270, 50);

        labelaSlika.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        panelDrugi.add(labelaSlika);
        labelaSlika.setBounds(-10, 0, 1470, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelPrvi, javax.swing.GroupLayout.DEFAULT_SIZE, 1450, Short.MAX_VALUE)
                    .addComponent(panelDrugi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrvi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDrugi, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        FormaZaKomisiju fzk = new FormaZaKomisiju();
        fzk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnNadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadjiActionPerformed
        // TODO add your handling code here:
         String kb =txtKartonskiBroj.getText();
        int kartonskiBroj = Integer.parseInt(kb);
//       
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setParametar(kartonskiBroj);
        kz.setOperacija(Operacije.VRATI_KARTON);
        
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        Karton karton = (Karton) so.getOdgovor();
        if(karton!=null){
            Kandidat kand = karton.getKandidat();
            kartonID = karton.getKartonID();
            if(kand==null){
                lblSifraPrijave.setText("Karton jos uvek nije spojen sa kandidatom!");
            }else{
                lblIme.setText(kand.getIme());
                lblPrezime.setText(kand.getPrezime());
                lblSifraPrijave.setText(kand.getSifraPrijave());
            }
            panelDrugi.setVisible(true);
            lblGrupa.setText(karton.getGrupaZadataka().getBrGrupe()+"");
            lblTest.setText(karton.getGrupaZadataka().getTest().getNazivTesta());
            
            ArrayList<Zadatak> zadaciKartona = karton.getListaOdg();
            ModelTabeleIzmenaKartona mtr = new ModelTabeleIzmenaKartona();
            mtr.setFik(this);
            mtr.setZadaci(zadaciKartona);
            tabelaZadaci.setModel(mtr);
        }else{
            JOptionPane.showMessageDialog(this, "Karton sa takvim kratonskim brojem ne postoji u bazi!");
            return;
       }

    }//GEN-LAST:event_btnNadjiActionPerformed

    private void btnIzmeniKartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniKartonActionPerformed
        // TODO add your handling code here:
        PomocIzmena pi = new PomocIzmena();
        pi.setKratonId(kartonID);
        ModelTabeleIzmenaKartona mtik = (ModelTabeleIzmenaKartona) tabelaZadaci.getModel();
         ArrayList<Zadatak> zadaciZaIzmenu = mtik.getZadaciZaIzmenu();
        if(zadaciZaIzmenu.size()==0){
            JOptionPane.showMessageDialog(this, "Morate prvo izmeniti karton!");
            return;
        }
        pi.setZadaciZaIzmenu(zadaciZaIzmenu);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.IZMENI_ZADATKE);
        kz.setParametar(pi);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        JOptionPane.showMessageDialog(this, so.getPoruka());
        return;
    }//GEN-LAST:event_btnIzmeniKartonActionPerformed

    private void txtKartonskiBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKartonskiBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKartonskiBrojActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaIzmenaKartona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrvi;
    private javax.swing.JButton btnIzmeniKarton;
    private javax.swing.JButton btnNadji;
    private javax.swing.JButton btnNazad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelaSlika;
    private javax.swing.JLabel lblGrupa;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JLabel lblSifraPrijave;
    private javax.swing.JLabel lblTest;
    private javax.swing.JPanel panelDrugi;
    private javax.swing.JTable tabelaZadaci;
    private javax.swing.JTextField txtKartonskiBroj;
    // End of variables declaration//GEN-END:variables

    public void obavestiLength() {
        JOptionPane.showMessageDialog(this, "Mozete uneti samo jednu vrednost!");
      return;
    }

    public void obavesti() {
         JOptionPane.showMessageDialog(this, "Mozete uneti A, B, C, D, E ili N");
      return;
    }
}
