/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.komisija;


import domen.GrupaZadatka;
import domen.Kandidat;
import domen.Karton;
import domen.Resenje;
import domen.Test;
import domen.Zadatak;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;

import modeli.ModelTabeleResenjaZadataka;
import modeli.ModelTabeleZadataka;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author PC
 */
public class FormaUnosKartona extends javax.swing.JFrame {

    /**
     * Creates new form FormaUnosKartona
     */
    public FormaUnosKartona() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x = tk.getScreenSize().width;
        int y = tk.getScreenSize().height;
        postaviKartonID();
        setSize(x, y);
       // vratiKartonId();
        popuniGrupuZadataka();
        lblTest.setVisible(false);
        srediTabelu();
       
        txtBrojUnosaKartona.setText("1");
        
        txtBrojUnosaKartona.setEnabled(false);
        
//        vratiBrUnosaKartona();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelOdgovora = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblTest = new javax.swing.JLabel();
        cmbGZ = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        btnSacuvajKarton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBrojKartona = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBrojUnosaKartona = new javax.swing.JTextField();
        txtKartonID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos kartona ");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos odgovora"));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        tabelOdgovora.setForeground(new java.awt.Color(102, 102, 102));
        tabelOdgovora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelOdgovora);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(260, 100, 610, 360);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Grupa zadataka: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 30, 104, 17);

        lblTest.setBackground(new java.awt.Color(204, 204, 204));
        lblTest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTest.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(lblTest);
        lblTest.setBounds(550, 20, 221, 31);

        cmbGZ.setForeground(new java.awt.Color(102, 102, 102));
        cmbGZ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGZActionPerformed(evt);
            }
        });
        jPanel1.add(cmbGZ);
        cmbGZ.setBounds(190, 30, 255, 20);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Izadji");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1060, 70, 170, 50);

        btnSacuvajKarton.setBackground(new java.awt.Color(153, 153, 153));
        btnSacuvajKarton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacuvajKarton.setForeground(new java.awt.Color(102, 102, 102));
        btnSacuvajKarton.setText("SACUVAJ KARTON");
        btnSacuvajKarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajKartonActionPerformed(evt);
            }
        });
        jPanel1.add(btnSacuvajKarton);
        btnSacuvajKarton.setBounds(1060, 413, 180, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1430, 630);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Karton"));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("KartonID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 40, 130, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Broj unosa kartona:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(410, 40, 210, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Broj kartona:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(880, 40, 130, 17);
        jPanel2.add(txtBrojKartona);
        txtBrojKartona.setBounds(1033, 30, 310, 30);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("[Broj kartona napisan na samom kartonu]");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(1100, 70, 230, 14);
        jPanel2.add(txtBrojUnosaKartona);
        txtBrojUnosaKartona.setBounds(640, 30, 220, 30);
        jPanel2.add(txtKartonID);
        txtKartonID.setBounds(180, 30, 223, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 20, 1410, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGZActionPerformed
        GrupaZadatka gz = (GrupaZadatka) cmbGZ.getSelectedItem();
        if (gz != null) {
            lblTest.setText(gz.getTest().toString());
            lblTest.setVisible(true);
            srediTabelu();
        }

    }//GEN-LAST:event_cmbGZActionPerformed

    private void btnSacuvajKartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajKartonActionPerformed
        String kid = txtKartonID.getText();
        String brUnosa = txtBrojUnosaKartona.getText();
        String brojKar = txtBrojKartona.getText();
        if (kid.isEmpty() || brUnosa.isEmpty() || brojKar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite broj kartona!");
            return;
        }

        GrupaZadatka gz = (GrupaZadatka) cmbGZ.getSelectedItem();
       ModelTabeleZadataka mtz = (ModelTabeleZadataka) tabelOdgovora.getModel();
       ArrayList<Zadatak> lz =mtz.vraiResenja();
       String regex = "[0-9]+";
       if(!brojKar.matches(regex)){
            JOptionPane.showMessageDialog(this, "Unesite broj za polje broj KARTONA!");
            txtBrojKartona.setText("");
            return;
       }
        int kartonID = Integer.parseInt(kid);
        int brojUnosa = Integer.parseInt(brUnosa);
        int brojKartona = Integer.parseInt(brojKar);
        Karton k = new Karton(kartonID, brojKartona, brojUnosa, gz);
        k.setListaOdg(lz);
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.SACUVAJ_KARTON, k);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        if(so.getOdgovor().equals("!")){
            JOptionPane.showMessageDialog(this, so.getPoruka());
        }else {
            JOptionPane.showMessageDialog(this, so.getPoruka());
        }
       
        //int
    }//GEN-LAST:event_btnSacuvajKartonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormaZaKomisiju fzk = new FormaZaKomisiju();
        fzk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaUnosKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaUnosKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaUnosKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaUnosKartona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaUnosKartona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajKarton;
    private javax.swing.JComboBox cmbGZ;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTest;
    private javax.swing.JTable tabelOdgovora;
    private javax.swing.JTextField txtBrojKartona;
    private javax.swing.JTextField txtBrojUnosaKartona;
    private javax.swing.JTextField txtKartonID;
    // End of variables declaration//GEN-END:variables

    

//    private void vratiBrUnosaKartona() {
//        String brKarton = txtBrojKartona.getText();
//        String regex = "[0-9]+";
//        if(regex)
//        int brKartona = Integer.parseInt(brKarton);
//        int brojUnosa = Kontroler.getInstance().vratiBrUnosa();
//        if(brojUnosa==1) {
//            txtBrojUnosaKartona.setText("PRVI UNOS!");
//        }
//        if(brojUnosa==2) {
//            txtBrojUnosaKartona.setText("DRUGI UNOS!");
//        }
//        if(brojUnosa>2) {
//            JOptionPane.showMessageDialog(this, "Ovaj karton je vec unet 2 puta!");
//        }
//                
//    }
    private void popuniGrupuZadataka() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_GRUPU_ZADATKA, null);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        ArrayList<GrupaZadatka> listGZ = (ArrayList<GrupaZadatka>) so.getOdgovor();

        cmbGZ.removeAllItems();

        for (GrupaZadatka grupaZadatka : listGZ) {
            cmbGZ.addItem(grupaZadatka);
        }

    }

    private void srediTabelu() {
        ModelTabeleZadataka mtz = new ModelTabeleZadataka(this);
        tabelOdgovora.setModel(mtz);
        GrupaZadatka gz = (GrupaZadatka) cmbGZ.getSelectedItem();
        Test t = gz.getTest();
        if (t.getTestID() == 1) {
            for (int i = 0; i < 20; i++) {
                mtz.dodajResenje(i + 1, ' ');
            }
        } else {
            for (int i = 0; i < 30; i++) {
                mtz.dodajResenje(i + 1, ' ');
            }
        }

    }

    private void postaviKartonID() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_MAX_ID_KARTONA, null);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        
        int br  = (int) so.getOdgovor();
        txtKartonID.setText(br+"");
        txtKartonID.setEnabled(false);
    }

    void postaviUnosK() {
        txtBrojUnosaKartona.setText("2");
    }

    public void obavesti() {
      JOptionPane.showMessageDialog(this, "Mozete uneti A, B, C, D, E ili N");
      return;
    }

    public void obavestiLength() {
        JOptionPane.showMessageDialog(this, "Mozete uneti samo jednu vrednost!");
      return;
    }
}
