/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.komisija;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import domen.Rang_Lista;
import domen.Stavka_Rang_Liste;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author PC
 */
public class FormaZaPDFs extends javax.swing.JFrame {

    /**
     * Creates new form FormaZaPDFs
     */
    public FormaZaPDFs() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x = (int) tk.getScreenSize().getWidth();
        int y = (int) tk.getScreenSize().getHeight();
        setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbSmer = new javax.swing.JComboBox<>();
        btnNazad = new javax.swing.JButton();
        btnKreiraj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setText("Molimo odaberite smer:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 80, 140, 20);

        cmbSmer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informacioni sistemi i tehnologije", "Menadzment", "Informacioni sistemi i tehnologije - sistem na daljinu" }));
        jPanel1.add(cmbSmer);
        cmbSmer.setBounds(250, 80, 290, 20);

        btnNazad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNazad);
        btnNazad.setBounds(980, 80, 150, 40);

        btnKreiraj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKreiraj.setText("Kreiraj pdf za odabrani smer");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });
        jPanel1.add(btnKreiraj);
        btnKreiraj.setBounds(670, 80, 230, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1540, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        FormaZaKomisiju fzk = new FormaZaKomisiju();
        fzk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        // TODO add your handling code here:
        String smer = (String) cmbSmer.getSelectedItem();
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setParametar(smer);
        kz.setOperacija(Operacije.VRATI_RANG_LISTU);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        Rang_Lista rl = (Rang_Lista) so.getOdgovor();

        System.out.println(so.getPoruka());

        try {
            String ime ="";
            if(smer.equals("Informacioni sistemi i tehnologije")){
                ime = "Informacioni_sistemi_i_tehnologije";
            }else if(smer.equals("Menadzment")){
                ime = "Menadzment";
            }else{
                ime = "Informacioni_sistemi_i_tehnologije_-_sistem_na_daljinu";
            }
            String file_name = "C:\\Mladenovic_Marija_42014\\MojaAplikacijaWebb\\web\\files" + ime + ".pdf";

            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(file_name));
            Font font3 = new Font(Font.FontFamily.TIMES_ROMAN, 14, Font.BOLD);
            document.open();
            
            Image image1 = Image.getInstance("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\logo.png");
            image1.setAlignment(Element.ALIGN_RIGHT);
            document.add(image1);
            Paragraph para = new Paragraph("Rang-lista za smer " + rl.getSmer(), font3);
            para.setAlignment(Element.ALIGN_CENTER);
            document.add(para);
            Paragraph para1 = new Paragraph("Godina: " + rl.getGodina(),font3);
            para1.setAlignment(Element.ALIGN_CENTER);
            document.add(para1);
             
            ArrayList<Stavka_Rang_Liste> stavke = rl.getStavke();
            
            PdfPTable table = new PdfPTable(4);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);
            table.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell c1 = new PdfPCell(new Phrase("Rang:",font3));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("Prezime:",font3));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("Ime:",font3));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("Broj poena:",font3));
            table.addCell(c1);
            for (Stavka_Rang_Liste stavka_Rang_Liste : stavke) {
                
               table.addCell(stavka_Rang_Liste.getRedniBroj()+".");
                table.addCell(stavka_Rang_Liste.getKandidat().getPrezime()+"");
                table.addCell(stavka_Rang_Liste.getKandidat().getIme()+ " ");
                
                table.addCell(stavka_Rang_Liste.getKandidat().getUkupanBrojPoena()+"");
                
            }
            document.add(table);
            
            document.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormaZaPDFs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(FormaZaPDFs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormaZaPDFs.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnKreirajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaZaPDFs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaZaPDFs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaZaPDFs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaZaPDFs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaZaPDFs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnNazad;
    private javax.swing.JComboBox<String> cmbSmer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
