/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.sluzbenik;

import domen.Clan;
import java.util.ArrayList;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import niti.NitKomboClan;

import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author PC
 */
public class FormaZaUnosClanova extends javax.swing.JDialog {

    /**
     * Creates new form FormaZaUnosClanova
     */
     NitKomboClan nit;
    public FormaZaUnosClanova(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        nit= new NitKomboClan(this);
        nit.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbClanovi = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Izaberi clana:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 60, 130, 22);

        cmbClanovi.setForeground(new java.awt.Color(102, 102, 102));
        cmbClanovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbClanovi);
        cmbClanovi.setBounds(180, 60, 306, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Izadji");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(539, 13, 110, 40);

        btnSacuvaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSacuvaj.setForeground(new java.awt.Color(102, 102, 102));
        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });
        jPanel2.add(btnSacuvaj);
        btnSacuvaj.setBounds(540, 190, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        Clan clan = (Clan) cmbClanovi.getSelectedItem();
        FormaUnosKomisije fuk = (FormaUnosKomisije) getParent();
        fuk.dodajClana(clan);
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nit.zatvoriNit();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaZaUnosClanova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaZaUnosClanova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaZaUnosClanova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaZaUnosClanova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormaZaUnosClanova dialog = new FormaZaUnosClanova(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbClanovi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public void srediKombo() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_CLANOVE, null);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        ArrayList<Clan> listac = (ArrayList<Clan>) so.getOdgovor();
        cmbClanovi.removeAllItems();
        FormaUnosKomisije fuk = (FormaUnosKomisije) getParent();
        ArrayList<Clan> lisC=  fuk.vratiList();
        
        if(lisC.size()==0){
            for(Clan clan : listac){
                 if(clan.getKomisijaID()==0) {
//                   
            cmbClanovi.addItem(clan);
//            
            }
            }
        }else{
            for(Clan clan : listac){
                 if(clan.getKomisijaID()==0 && !lisC.contains(clan)) {
//                   
            cmbClanovi.addItem(clan);
//            
            }
        }
//        
//        for (Clan clan : listac) {
//            if(lisC.size()==0){
//                 if(clan.getKomisijaID()==0) {
//                   
//            cmbClanovi.addItem(clan);
//            
//            }
//            }
//            else if(!lisC.contains(clan)){
//                 if(clan.getKomisijaID()==0) {
//                   
//            cmbClanovi.addItem(clan);
//            
//            }
//             }
//            
//            
//        }
    }
    }

}
