/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.sluzbenik;

import forme.sluzbenik.FormaZaSluzbenika;
import domen.Clan;
import domen.Drzevljanstvo;
import domen.Kandidat;
import domen.Nacionalnost;
import domen.SrednjaSkola;
import domen.ZanimanjeRoditelja;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;

import modeli.ModelTabeleKomisija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author PC
 */
public class FormaUnosKandidata extends javax.swing.JFrame {

    boolean zenskiPol = false;

    /**
     * Creates new form FormaUnosKandidata
     */
    public FormaUnosKandidata() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x = (int) tk.getScreenSize().getWidth();
        int y = (int) tk.getScreenSize().getHeight();
        setSize(x, y);
        srediKomboDrzevljanstvo();
        srediKomboSifraZanimanja();
        srediKomboNacionalnost();
        srediKomboSifraSrednjeSkole();
        txtPlus381.setText("+");
        txtPlusFiksni.setText("+");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPol = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtImeKandidata = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtImeRoditelja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRMuski = new javax.swing.JRadioButton();
        jRZenski = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cmbDrzavljanstvo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbSifraZanimanja = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbNacionalnost = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbSifraSkole = new javax.swing.JComboBox();
        txtJMBG = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMobilniTel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFixTel = new javax.swing.JTextField();
        txtPlus381 = new javax.swing.JTextField();
        txtPlusFiksni = new javax.swing.JTextField();
        btnUnesiKandidata = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtBrBodovaIzSkole = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtxEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbSmer = new javax.swing.JComboBox();
        btnVerifikuj = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGlavniMeni = new javax.swing.JButton();
        txtSifraPrijave = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos novog kanidata");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos kandidata"));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Ime:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 40, 28, 20);

        txtImeKandidata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtImeKandidata.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtImeKandidata);
        txtImeKandidata.setBounds(160, 40, 1070, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Prezime:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 90, 52, 17);

        txtPrezime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrezime.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtPrezime);
        txtPrezime.setBounds(160, 80, 1070, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Ime jednog roditelja:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 130, 127, 17);

        txtImeRoditelja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtImeRoditelja.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtImeRoditelja);
        txtImeRoditelja.setBounds(160, 120, 1070, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Pol:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 23, 17);

        buttonGroupPol.add(jRMuski);
        jRMuski.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRMuski.setForeground(new java.awt.Color(102, 102, 102));
        jRMuski.setText("M");
        jRMuski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMuskiActionPerformed(evt);
            }
        });
        jPanel1.add(jRMuski);
        jRMuski.setBounds(30, 190, 35, 25);

        buttonGroupPol.add(jRZenski);
        jRZenski.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRZenski.setForeground(new java.awt.Color(102, 102, 102));
        jRZenski.setText("Z");
        jRZenski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRZenskiActionPerformed(evt);
            }
        });
        jPanel1.add(jRZenski);
        jRZenski.setBounds(30, 220, 33, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Drzavljanstvo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 170, 89, 17);

        cmbDrzavljanstvo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDrzavljanstvo.setForeground(new java.awt.Color(102, 102, 102));
        cmbDrzavljanstvo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDrzavljanstvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDrzavljanstvoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbDrzavljanstvo);
        cmbDrzavljanstvo.setBounds(150, 210, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Sifra zanimanja roditelja:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 170, 148, 20);

        cmbSifraZanimanja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSifraZanimanja.setForeground(new java.awt.Color(102, 102, 102));
        cmbSifraZanimanja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbSifraZanimanja);
        cmbSifraZanimanja.setBounds(400, 210, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nacionalnost:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(760, 170, 82, 17);

        cmbNacionalnost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbNacionalnost.setForeground(new java.awt.Color(102, 102, 102));
        cmbNacionalnost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbNacionalnost);
        cmbNacionalnost.setBounds(690, 210, 200, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Sifra srednje skole:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1060, 170, 140, 30);

        cmbSifraSkole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSifraSkole.setForeground(new java.awt.Color(102, 102, 102));
        cmbSifraSkole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbSifraSkole);
        cmbSifraSkole.setBounds(1010, 210, 210, 30);

        txtJMBG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJMBG.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtJMBG);
        txtJMBG.setBounds(150, 260, 1080, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("JMBG:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 270, 38, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Mobilni:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 310, 90, 20);

        txtMobilniTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMobilniTel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtMobilniTel);
        txtMobilniTel.setBounds(240, 300, 280, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Fiksni telefon:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(592, 310, 140, 17);

        txtFixTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFixTel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtFixTel);
        txtFixTel.setBounds(900, 300, 330, 30);

        txtPlus381.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlus381.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtPlus381);
        txtPlus381.setBounds(150, 300, 70, 30);

        txtPlusFiksni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlusFiksni.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtPlusFiksni);
        txtPlusFiksni.setBounds(800, 300, 80, 30);

        btnUnesiKandidata.setBackground(new java.awt.Color(153, 153, 153));
        btnUnesiKandidata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUnesiKandidata.setForeground(new java.awt.Color(102, 102, 102));
        btnUnesiKandidata.setText("Unesi kandidata");
        btnUnesiKandidata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiKandidataActionPerformed(evt);
            }
        });
        jPanel1.add(btnUnesiKandidata);
        btnUnesiKandidata.setBounds(920, 470, 180, 60);

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Broj bodova iz skole:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 360, 130, 30);

        txtBrBodovaIzSkole.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtBrBodovaIzSkole);
        txtBrBodovaIzSkole.setBounds(150, 360, 370, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("E-mail:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(590, 360, 120, 30);

        txtxEmail.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtxEmail);
        txtxEmail.setBounds(800, 360, 430, 30);

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Smer:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 400, 110, 30);

        cmbSmer.setForeground(new java.awt.Color(102, 102, 102));
        cmbSmer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.INFORMACIONI SISTEMI", "2.MENADZMENT", "3.INFORMACIONI SISTEMI-SISTEM NA DALJINU", "4.SVA TRI SMERA" }));
        jPanel1.add(cmbSmer);
        cmbSmer.setBounds(150, 400, 350, 30);

        btnVerifikuj.setBackground(new java.awt.Color(153, 153, 153));
        btnVerifikuj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVerifikuj.setForeground(new java.awt.Color(102, 102, 102));
        btnVerifikuj.setText("Verifikuj kandidata");
        btnVerifikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifikujActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerifikuj);
        btnVerifikuj.setBounds(660, 473, 210, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 14, 1380, 570);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" "));
        jPanel2.setLayout(null);

        btnGlavniMeni.setBackground(new java.awt.Color(153, 153, 153));
        btnGlavniMeni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGlavniMeni.setForeground(new java.awt.Color(102, 102, 102));
        btnGlavniMeni.setText("Izadji");
        btnGlavniMeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGlavniMeniActionPerformed(evt);
            }
        });
        jPanel2.add(btnGlavniMeni);
        btnGlavniMeni.setBounds(1070, 50, 150, 50);

        txtSifraPrijave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSifraPrijave.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(txtSifraPrijave);
        txtSifraPrijave.setBounds(240, 50, 170, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Broj prijave:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 60, 75, 17);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 14, 1370, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1385, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRZenskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRZenskiActionPerformed
        zenskiPol = true;
    }//GEN-LAST:event_jRZenskiActionPerformed

    private void btnGlavniMeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGlavniMeniActionPerformed
        FormaZaSluzbenika fzs = new FormaZaSluzbenika();
        fzs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGlavniMeniActionPerformed

    private void btnUnesiKandidataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiKandidataActionPerformed
        String brojP = txtSifraPrijave.getText();
        String ime = txtImeKandidata.getText();
        String imeRoditelja = txtImeRoditelja.getText();
        String prezime = txtPrezime.getText();
        String pol;
        String email = txtxEmail.getText();
        String smeer = (String) cmbSmer.getSelectedItem();
        String brBodovaSk = txtBrBodovaIzSkole.getText();
        
        if (zenskiPol == true) {
            pol = "Zenski";
        } else {
            pol = "Muski";
        }
        Drzevljanstvo drzevlj = (Drzevljanstvo) cmbDrzavljanstvo.getSelectedItem();
        ZanimanjeRoditelja z = (ZanimanjeRoditelja) cmbSifraZanimanja.getSelectedItem();
        Nacionalnost nac = (Nacionalnost) cmbNacionalnost.getSelectedItem();
        SrednjaSkola ss = (SrednjaSkola) cmbSifraSkole.getSelectedItem();
        String jmbg = txtJMBG.getText();
        String mobilni = txtMobilniTel.getText();
        String fiksni = txtFixTel.getText();
        String plus381= txtPlus381.getText();
        String plusF= txtPlusFiksni.getText();
        
        if (brojP.isEmpty() || ime.isEmpty() || imeRoditelja.isEmpty() || prezime.isEmpty() || pol.isEmpty() || drzevlj == null
                || z == null || nac == null || email.isEmpty()||smeer.isEmpty()|| brBodovaSk.isEmpty() || ss == null || jmbg.isEmpty() || mobilni.isEmpty() || fiksni.isEmpty() || plus381.isEmpty() || plusF.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite sva polja!");
            return;

        }
        
        String regex = "[0-9]+";

        if (!mobilni.matches(regex)) {
            JOptionPane.showMessageDialog(this, "Unesite broj za polje mobilni telefon!");
            txtMobilniTel.setText("");
            return;
        }
        
        regex = "'+'[0-9]";
        if(plus381.matches(regex)){
            JOptionPane.showMessageDialog(this, "Unesite pozivni broj za polje mobilni u formatu +XXX!");
            txtPlus381.setText("+");
            return;
        }
        int brojPrijave = 0;
        regex = "[0-9]+";
        if (brojP.matches(regex)) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Unesite broj za polje BROJ PRIJAVE!");
            txtSifraPrijave.setText("");
            return;
        }
        
        if(jmbg.length()!=13) {
            JOptionPane.showMessageDialog(this, "JMBG ima 13 cifara!");
            return;
        }
        String dan = jmbg.substring(0, 2);
        
        int d = Integer.parseInt(dan);
        if(dan.equals("00")) {
            JOptionPane.showMessageDialog(this, "Prve dve cifre JMBG-a predstavljaju dane u mesecu [1-31]!");
            return;
        }
        if(d>31){
            JOptionPane.showMessageDialog(this, "Prve dve cifre JMBG-a predstavljaju dane u mesecu [1-31]!");
            return;
        
        }
        String mesec = jmbg.substring(2, 4);
        
        int m = Integer.parseInt(mesec);
        if(mesec.equals("00")) {
            JOptionPane.showMessageDialog(this, "Treca i cetvrta cifra JMBG-a predstavljaju mesece u godini [1-12]!");
            return;
        }
        if(m>12) {
            JOptionPane.showMessageDialog(this, "Treca i cetvrta cifra JMBG-a predstavljaju mesece u godini [1-12]!");
            return;
        }
        boolean tr = false;
        for (int i = 0; i < email.length(); i++) {
            if(email.charAt(i)=='@'){
                tr= true;
            }
        }
        
        if(!tr) {
           JOptionPane.showMessageDialog(this, "E-mail treba da sadrzi @!");
            txtxEmail.setText("");
            return; 
        }
//        1.INFORMACIONI SISTEMI
//2.MENADZMENT
//3.INFORMACIONI SISTEMI-SISTEM NA DALJINU
//4.SVA TRI SMERA
            int smer = 0;
        if(smeer.equals("1.INFORMACIONI SISTEMI")){
            smer = 1;
        }
        if(smeer.equals("2.MENADZMENT")) {
            smer =2;
        }
         if(smeer.equals("3.INFORMACIONI SISTEMI-SISTEM NA DALJINU")) {
            smer =3;
        }
         if(smeer.equals("4.SVA TRI SMERA")) {
            smer =4;
        }
        regex = "[0-9]+";
        
        double brBodSkola = Double.parseDouble(brBodovaSk);
        
        if(!fiksni.matches(regex)){
            JOptionPane.showMessageDialog(this, "Unesite fiksni telefon u formatu 01x/xxxxxxx");
            txtFixTel.setText("");
            return;
        }
        regex = "'+'[0-9]";
        
        if(plusF.matches(regex)){
             JOptionPane.showMessageDialog(this, "Unesite pozivni broj u formatu +XXX");
             txtPlusFiksni.setText("+");
            return;
        }
        Kandidat kandidat = new Kandidat(brojP, jmbg, ime, imeRoditelja, pol, prezime, plus381+mobilni, plusF+fiksni, ss, nac, z, drzevlj,email,brBodSkola,smer);
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.UNOS_KANDIDATA, kandidat);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        System.out.println("Primio");
        if(so.getOdgovor().equals("!")){
            JOptionPane.showMessageDialog(this, so.getPoruka());
        }else {
             JOptionPane.showMessageDialog(this, so.getPoruka());
        }
    }//GEN-LAST:event_btnUnesiKandidataActionPerformed

    private void jRMuskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMuskiActionPerformed
        zenskiPol = false;
    }//GEN-LAST:event_jRMuskiActionPerformed

    private void cmbDrzavljanstvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDrzavljanstvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDrzavljanstvoActionPerformed

    private void btnVerifikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikujActionPerformed
        // TODO add your handling code here:
       String email = txtxEmail.getText();
       if(email.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Unesite email!");
       }
                
                boolean tr = false;
        for (int i = 0; i < email.length(); i++) {
            if(email.charAt(i)=='@'){
                tr= true;
            }
        }
        
        if(!tr) {
           JOptionPane.showMessageDialog(this, "E-mail treba da sadrzi @!");
            txtxEmail.setText("");
            return; 
        }
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_KANDIDATA_ZA_VERIFIKACIJU, email);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        if(so.getOdgovor()==null){
            JOptionPane.showMessageDialog(this, so.getPoruka());
            return;
        } else {
             Kandidat kandidat = (Kandidat) so.getOdgovor();
        txtImeKandidata.setText(kandidat.getIme());
        txtPrezime.setText(kandidat.getPrezime());
        txtImeRoditelja.setText(kandidat.getImeRoditelja());
        txtFixTel.setText(kandidat.getFiksni());
        txtMobilniTel.setText(kandidat.getMobilni());
        txtJMBG.setText(kandidat.getJmbg());
        JOptionPane.showMessageDialog(this, so.getPoruka());
        }
       
        
        
        
    }//GEN-LAST:event_btnVerifikujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaUnosKandidata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaUnosKandidata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaUnosKandidata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaUnosKandidata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaUnosKandidata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGlavniMeni;
    private javax.swing.JButton btnUnesiKandidata;
    private javax.swing.JButton btnVerifikuj;
    private javax.swing.ButtonGroup buttonGroupPol;
    private javax.swing.JComboBox cmbDrzavljanstvo;
    private javax.swing.JComboBox cmbNacionalnost;
    private javax.swing.JComboBox cmbSifraSkole;
    private javax.swing.JComboBox cmbSifraZanimanja;
    private javax.swing.JComboBox cmbSmer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRMuski;
    private javax.swing.JRadioButton jRZenski;
    private javax.swing.JTextField txtBrBodovaIzSkole;
    private javax.swing.JTextField txtFixTel;
    private javax.swing.JTextField txtImeKandidata;
    private javax.swing.JTextField txtImeRoditelja;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtMobilniTel;
    private javax.swing.JTextField txtPlus381;
    private javax.swing.JTextField txtPlusFiksni;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtSifraPrijave;
    private javax.swing.JTextField txtxEmail;
    // End of variables declaration//GEN-END:variables

    private void srediKomboDrzevljanstvo() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_DRZ, null);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        System.out.println("Primio");
        ArrayList<Drzevljanstvo> listaD = (ArrayList<Drzevljanstvo>) so.getOdgovor();
        cmbDrzavljanstvo.removeAllItems();

        for (Drzevljanstvo drzevljanstvo : listaD) {
            cmbDrzavljanstvo.addItem(drzevljanstvo);
        }
    }

    private void srediKomboSifraZanimanja() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_SIF_ZANIM, null);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        ArrayList<ZanimanjeRoditelja> listaSZ = (ArrayList<ZanimanjeRoditelja>) so.getOdgovor();
        cmbSifraZanimanja.removeAllItems();

        for (ZanimanjeRoditelja zanimanjeRoditelja : listaSZ) {
            cmbSifraZanimanja.addItem(zanimanjeRoditelja);
        }
    }

    private void srediKomboNacionalnost() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_NAC, null);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        ArrayList<Nacionalnost> listaN = (ArrayList<Nacionalnost>) so.getOdgovor();
        cmbNacionalnost.removeAllItems();

        for (Nacionalnost nacionalnost : listaN) {
            cmbNacionalnost.addItem(nacionalnost);
        }
    }

    private void srediKomboSifraSrednjeSkole() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_SIF_SS, null);
        KomunikacijaSaServerom.getInstance().posaljiKZ(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().prihvatiSO();
        ArrayList<SrednjaSkola> listaSS = (ArrayList<SrednjaSkola>) so.getOdgovor();
        cmbSifraSkole.removeAllItems();

        for (SrednjaSkola srednjaSkola : listaSS) {
            cmbSifraSkole.addItem(srednjaSkola);
        }
    }

}
